pipeline:
  identifier: Build_Mayur_Girdhar_test_site_1713945540803
  name: Build test-site
  orgIdentifier: default
  projectIdentifier: mgpreprod
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1713945518564
        repoName: Mayur-Girdhar/test-site
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: build-run-step
                  identifier: buildrunstep
                  spec:
                    shell: Sh
                    command: |
                      ls 
                      pwd 
                      cd /home/ubuntu/
                      ls
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
